"""F29: codebase tree generation tests.

The SteeringRuntime._publish_codebase_tree() method scans the repo root at daemon
startup and publishes a text tree to steering/codebase.json via SteeringChannel.
These tests verify the tree content, exclusion rules, and channel wiring.
"""

import json
import os
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from src.agent.steering.channel import SteeringChannel
from src.agent.steering.runtime import _REPO_ROOT, SteeringRuntime


class TestCodebaseTree:
    """Verify the tree text generated by _publish_codebase_tree()."""

    @pytest.fixture
    def tmp_steering_dir(self):
        with tempfile.TemporaryDirectory() as td:
            yield td

    def test_tree_has_root_prefix(self, tmp_steering_dir):
        """The tree begins with the AUTOSTOCK_ROOT placeholder."""
        rt = self._make_runtime(tmp_steering_dir)
        lines = self._capture_tree(rt)
        assert any("{AUTOSTOCK_ROOT}" in line for line in lines)

    def test_tree_includes_core_packages(self, tmp_steering_dir):
        """Key source directories appear with their descriptions."""
        rt = self._make_runtime(tmp_steering_dir)
        tree = self._capture_tree_text(rt)
        # Top-level dirs
        assert "src/" in tree
        assert "operator-console/" in tree
        assert "config/" in tree
        assert "tests/" in tree
        # Sub-packages (one level deep in src/)
        assert "src/agent" in tree or "agent/" in tree
        assert "src/risk" in tree or "risk/" in tree
        assert "src/execution" in tree or "execution/" in tree
        assert "src/core" in tree or "core/" in tree

    def test_tree_excludes_build_artifacts(self, tmp_steering_dir):
        """Build artifacts and caches are excluded."""
        rt = self._make_runtime(tmp_steering_dir)
        tree = self._capture_tree_text(rt)
        assert "__pycache__" not in tree
        assert ".git" not in tree
        assert "node_modules" not in tree
        assert ".mypy_cache" not in tree
        assert ".pytest_cache" not in tree

    def test_tree_includes_package_descriptions(self, tmp_steering_dir):
        """Package directories carry a one-line description comment."""
        rt = self._make_runtime(tmp_steering_dir)
        tree = self._capture_tree_text(rt)
        # A few known descriptions should appear
        assert "risk" in tree.lower()
        assert "agent" in tree.lower()

    def test_key_files_listed(self, tmp_steering_dir):
        """Important individual files (main.py, config files) appear."""
        rt = self._make_runtime(tmp_steering_dir)
        tree = self._capture_tree_text(rt)
        assert "main.py" in tree

    # ---- helpers -----------------------------------------------------------

    def _make_runtime(self, steering_dir):
        """Minimal SteeringRuntime with mocked executor/orchestrator."""
        ws = Path(steering_dir) / "workspace"
        ws.mkdir(parents=True, exist_ok=True)
        executor = MagicMock()
        executor.journal.root = ws  # must be a Path, not str (CommandHandler uses /)
        executor.broker = MagicMock()
        executor.risk_manager = MagicMock()
        executor.data_provider = MagicMock()
        orchestrator = MagicMock()
        return SteeringRuntime(executor, orchestrator, steering_dir=steering_dir)

    def _capture_tree(self, rt: SteeringRuntime):
        """Call _publish_codebase_tree and return the lines written to channel."""
        rt._publish_codebase_tree()
        path = str(rt.channel.codebase_file)
        raw = Path(path).read_text(encoding="utf-8")
        payload = json.loads(raw)
        assert "tree" in payload
        return payload["tree"].split("\n")

    def _capture_tree_text(self, rt: SteeringRuntime) -> str:
        """Call _publish_codebase_tree and return the full tree text."""
        rt._publish_codebase_tree()
        path = str(rt.channel.codebase_file)
        raw = Path(path).read_text(encoding="utf-8")
        payload = json.loads(raw)
        return payload["tree"]


class TestCodebaseChannel:
    """Verify SteeringChannel.publish_codebase()."""

    def test_publish_codebase_writes_atomic(self, tmp_path):
        ch = SteeringChannel(str(tmp_path), token="test")
        ch.publish_codebase("root/\n  src/")
        raw = (tmp_path / "codebase.json").read_text(encoding="utf-8")
        payload = json.loads(raw)
        assert payload["tree"] == "root/\n  src/"
        assert "published_at" in payload

    def test_publish_codebase_overwrites(self, tmp_path):
        ch = SteeringChannel(str(tmp_path), token="test")
        ch.publish_codebase("first")
        ch.publish_codebase("second")
        raw = (tmp_path / "codebase.json").read_text(encoding="utf-8")
        assert json.loads(raw)["tree"] == "second"

    def test_codebase_file_no_torn_read(self, tmp_path):
        """codebase.json is never partially written (atomic write)."""
        ch = SteeringChannel(str(tmp_path), token="test")
        ch.publish_codebase("line 1\nline 2\nline 3")
        # Read back — should be valid JSON (not torn).
        payload = json.loads((tmp_path / "codebase.json").read_text(encoding="utf-8"))
        assert "line 1" in payload["tree"]


class TestCodebaseTreeExcludes:
    """Verify exclusion rules are applied correctly on a synthetic tree."""

    @pytest.fixture
    def tmp_repo(self, tmp_path):
        """Create a minimal repo-like structure with some excluded dirs."""
        (tmp_path / "src" / "agent").mkdir(parents=True)
        (tmp_path / "src" / "core").mkdir(parents=True)
        (tmp_path / "src" / "__pycache__").mkdir(parents=True)
        (tmp_path / "operator-console" / "src").mkdir(parents=True)
        (tmp_path / "node_modules").mkdir(parents=True)
        (tmp_path / ".git").mkdir(parents=True)
        (tmp_path / "main.py").write_text("")
        (tmp_path / "config" / "settings.yaml").mkdir(parents=True)
        return tmp_path

    def test_excludes_hidden_dirs(self, tmp_repo):
        """.git and similar hidden dirs are not listed."""
        assert ".git" in SteeringRuntime._TREE_EXCLUDE
        assert "__pycache__" in SteeringRuntime._TREE_EXCLUDE
        assert "node_modules" in SteeringRuntime._TREE_EXCLUDE

    def test_synthetic_tree_with_root_override(self, tmp_repo):
        """Tree generated from a synthetic root only lists non-excluded entries."""
        # Create a minimal SteeringRuntime then call _publish_codebase_tree
        # with root pointing at the synthetic tmp_repo.
        executor = MagicMock()
        executor.journal.root = tmp_repo / "workspace"
        (tmp_repo / "workspace").mkdir()
        executor.broker = MagicMock()
        executor.risk_manager = MagicMock()
        executor.data_provider = MagicMock()
        orchestrator = MagicMock()
        rt = SteeringRuntime(executor, orchestrator,
                             steering_dir=str(tmp_repo / "steering"))
        rt._publish_codebase_tree(root=tmp_repo)

        raw = (tmp_repo / "steering" / "codebase.json").read_text(encoding="utf-8")
        payload = json.loads(raw)
        tree = payload["tree"]

        # Should include known packages
        assert "src/" in tree
        assert "operator-console/" in tree
        assert "config/" in tree
        assert "main.py" in tree
        # Should NOT include excluded dirs
        assert "__pycache__" not in tree
        assert "node_modules" not in tree
        assert ".git" not in tree

    def test_egg_info_glob_excluded(self, tmp_path):
        """Directories matching *.egg-info are excluded via fnmatch glob."""
        (tmp_path / "autostock.egg-info").mkdir()
        (tmp_path / "src").mkdir()
        assert SteeringRuntime._is_excluded("autostock.egg-info") is True
        assert SteeringRuntime._is_excluded("src") is False
        assert SteeringRuntime._is_excluded("my_package.egg-info") is True
