"""Privilege separation (BR-10): confine the agent + carry the operator token.

Two concerns:

1. **PreToolUse deny-hook** (the primary structural boundary, BR-10.1). Run by the
   agent's ``claude -p`` session before every file tool, it DENIES any Read/Write/
   Edit/Glob/Grep/Notebook path that resolves outside the agent's workspace -- so the
   agent cannot reach the repo-root ``steering/`` command channel or the operator
   token even via an absolute path. This module is pure stdlib so it works as a
   standalone hook script (`python3 .../security.py`) with no PYTHONPATH.

2. **Operator token** (BR-10.2): generated by the daemon, passed out-of-band to the
   operator process via env, and SCRUBBED from the env the daemon hands to the agent
   subprocess (so `env = dict(os.environ)` in session.py cannot leak it).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

TOKEN_ENV_VAR = "STEERING_OPERATOR_TOKEN"
_HOOK_TOOLS = "Read|Write|Edit|MultiEdit|Glob|Grep|NotebookEdit"


# --------------------------------------------------------------------------- #
# PreToolUse hook
# --------------------------------------------------------------------------- #
def path_is_inside(candidate: str, root: str) -> bool:
    """True iff ``candidate`` (abs or relative-to-cwd) resolves under ``root``."""
    try:
        c = os.path.realpath(candidate)
        r = os.path.realpath(root)
        return c == r or os.path.commonpath([c, r]) == r
    except (ValueError, OSError):
        return False  # different drive / unresolvable -> treat as outside (fail-closed)


def _candidate_path(tool_input: dict) -> str | None:
    for key in ("file_path", "notebook_path", "path"):
        v = tool_input.get(key)
        if isinstance(v, str) and v:
            return v
    return None


def evaluate(tool_name: str, tool_input: dict, root: str) -> tuple[bool, str]:
    """Return (allow, reason). Deny only when an explicit path is outside root."""
    cand = _candidate_path(tool_input or {})
    if cand is None:
        return True, ""  # no path arg (e.g. a workspace-relative Glob) -> allow
    if path_is_inside(cand, root):
        return True, ""
    return False, (
        f"Denied: {tool_name} path '{cand}' is outside the agent workspace "
        f"({root}). The steering command channel and operator token are off-limits "
        f"to the trading agent (advisor-only)."
    )


def main() -> int:
    """Hook entry: read the PreToolUse JSON on stdin; exit 2 (block) if outside."""
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0  # never block on a malformed hook payload (don't brick the agent)
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    allow, reason = evaluate(data.get("tool_name", ""), data.get("tool_input", {}) or {}, root)
    if not allow:
        print(reason, file=sys.stderr)  # stderr is surfaced to the agent on exit 2
        return 2
    return 0


# --------------------------------------------------------------------------- #
# settings.json generation + token handling (daemon side)
# --------------------------------------------------------------------------- #
def write_agent_hook_settings(workspace_dir: str | Path) -> Path:
    """Write ``<workspace>/.claude/settings.json`` registering this module as the
    PreToolUse deny-hook for the agent session. Returns the settings path."""
    workspace_dir = Path(workspace_dir)
    settings_dir = workspace_dir / ".claude"
    settings_dir.mkdir(parents=True, exist_ok=True)
    hook_cmd = f"python3 {Path(__file__).resolve()}"
    settings = {
        "hooks": {
            "PreToolUse": [
                {"matcher": _HOOK_TOOLS,
                 "hooks": [{"type": "command", "command": hook_cmd}]}
            ]
        }
    }
    path = settings_dir / "settings.json"
    path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
    return path


def issue_token() -> str:
    import secrets
    return secrets.token_urlsafe(32)


def scrub_agent_env(env: dict) -> dict:
    """Remove the operator token from an env dict before spawning the agent
    (BR-10.2) -- ``session._invoke`` does ``env = dict(os.environ)`` which would
    otherwise copy the daemon's token to the agent."""
    env.pop(TOKEN_ENV_VAR, None)
    return env


if __name__ == "__main__":
    sys.exit(main())
